version: '3.8'

services:
  database:
    image: postgres:12-alpine
    container_name: priceHunt-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: priceHunt-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: priceHunt-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/priceHunt-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  pgdata:
